### ISSUE TITLE
Not hiding development mode

### ISSUE THREAD

**Issue by gabriel20xx** [xfqwdsj/IAmNotADeveloper#79] opened 2024-10-05 11:41 UTC
**Describe the bug**
The module is not working for me. Ruru and other apps detect development mode as enabled.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Poco F3
 - OS: CrDroid, Android 14

**Additional context**

**Comment by xfqwdsj** [comment] 2024-10-05 11:46
Show me your test result

![Result](https://github.com/user-attachments/assets/96db2366-7800-42d1-9aac-973f4bf4cd99)

**Comment by xfqwdsj** [comment] 2024-10-05 11:53
May be duplicate of #4

**Comment by gabriel20xx** [comment] 2024-10-06 11:26
> Show me your test result
> 
> ![Result](https://github.com/user-attachments/assets/96db2366-7800-42d1-9aac-973f4bf4cd99)
> 

The test result is like it should be, but it's not working with other apps

**Comment by xfqwdsj** [comment] 2024-10-10 14:33
No enough information, consider this as a duplicate of #4.

**Closed by xfqwdsj** 2024-10-10 14:33 UTC
Labels: bug
